blank_issues_enabled: false
contact_links:
  - name: Report a Security Vulnerability
    url: https://github.com/{{github_username}}/{{project-name}}/security/advisories/new
    about: Privately report a vulnerability. Do NOT use standard issues.
