[package]
name = "{{project-name}}"
version.workspace = true
authors.workspace = true
{% assign cat_list = categories | split: "," -%}
categories = [{% for c in cat_list %}"{{ c | strip }}"{% unless forloop.last %}, {% endunless %}{% endfor %}]
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "{{description}}"

[dependencies]
{{project-name}}-core.workspace = true

[dev-dependencies]

[lints]
workspace = true

[[bin]]
name = "{{project-name}}"
path = "src/main.rs"

[package.metadata.binstall]
pkg-url = "https://github.com/{{github_username}}/{ name }/releases/download/v{ version }/{ name }-{ target }.tar.xz"
bin-dir = "{ name }-{ target }/{ bin }{ binary-ext }"
pkg-fmt = "txz"
